<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //block 1: console.log(a) will give an undefiend value because it is initialized under after the call 
        console.log("------------------------Block 1------------------------");
        function funcA() {
            console.log(a);
            console.log(foo());
            var a = 1;
            function foo() {
                return 2;
            }
        }
        funcA();

        //block 2: at line 36 it prints the 'Aurelio' name because we call the function related to that object, but at line 38 it prints 'John' because we clone only the function at line 37 and when it needs to run this.fullName it can see only 'john' in his scope     var fullName = 'John Doe';
        console.log("------------------------Block 2------------------------");
        var obj = {
            fullName: 'Colin Ihrig',
            prop: {
                fullName: 'Aurelio De Rosa',
                getFullName: function () {
                    return this.fullName;
                }
            }
        };
        console.log(obj.prop.getFullName());
        var test = obj.prop.getFullName;
        console.log(test());


        //block 6 at line 44 it gives undefiend because of hoisting, it can see that there is a variable but can't see its value, while in line 46 it can see the value of f=1 before calling the function so the result is 1
        console.log("------------------------Block 6------------------------");
        function funcE() {
            console.log("Value of f in local scope: ", f);
        }
        console.log("Value of f in global scope: ", f);
        var f = 1;
        funcE();

        //block 3 I think that line 58 gives undefinded because a is withen the function scope and cant be seen out of it, but it treats b as a global varible so it can be seen at line 59
        console.log(" ------------------------Block 3------------------------");
        function funcB() {
            let a = b = 0;
            a++;
            return a;
        }
        funcB();
        console.log(typeof a);
        console.log(typeof b);

        //block 4 it will print 2 twice because of hoisting, first it will see the function at line 63 then it will override it with function of line 67 then it will go  back to the line 66 and run it, so the value it sees only 2
        console.log(" ------------------------Block 4------------------------");
        function funcC() {
            console.log("1");
        }
        funcC();
        function funcC() {
            console.log("2");
        }
        funcC();

        //block 5 in line 78 it gives 1 because ut treats d as a global variable created accidentally while in line 83 it can't see e because it is in the function scope
        console.log(" ------------------------Block 5------------------------");
        function funcD1() {
            d = 1;
        }
        funcD1();
        console.log(d);
        function funcD2() {
            var e = 1;
        }
        funcD2();
        console.log(e);

    </script>
</body>

</html>